version: "2"
# Access site at http://${NAME}.test
services:
  php:
    image: wodby/drupal-php:${PHP_WODBY_TAG}
    environment:
      PHP_DOCROOT: ${DOCROOT} # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog.test:1025
      PHP_XDEBUG_ENABLED: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1
      PHP_MAX_INPUT_VARS: 15000
      PHP_MEMORY_LIMIT: 2048M
      PHP_MAX_EXECUTION_TIME: 360
    volumes:
    - ./:/var/www/html
    networks:
    - default
    - common-apps_default
    dns:
    - 172.17.0.1
  nginx:
    container_name: ${NAME}
    image: wodby/drupal-nginx:${DRUPAL_VERSION}-${NGINX_VERSION}
    environment:
      NGINX_SERVER_NAME: ${NAME}.test
      NGINX_SERVER_ROOT: /var/www/html/${DOCROOT}
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_DOCROOT: ${DOCROOT} # Relative path inside the /var/www/html/ directory.
    labels:
    - traefik.backend=${NAME}-nginx
    - traefik.frontend.rule=Host:${NAME}.test
    - traefik.port=80
    - traefik.docker.network=common-apps_default
    volumes:
    - ./:/var/www/html
    links:
    - php
    networks:
    - default
    - common-apps_default
  # Solr for D7 (using solr 4.x).
  #  # Solr: configure search_api_solr to connect to hostname: solr and solr path: /solr
  solr:
    image: twinbit/docker-drupal-solr
    container_name: ${NAME}-solr
    volumes:
    - ./sites/all/modules/contrib/search_api_solr/solr-conf/4.x:/myconfig
    - ./.solr-data:/opt/solr/example/solr/collection1/data
    labels:
    - traefik.backend=${NAME}-solr
    - traefik.frontend.rule=Host:${NAME}-solr.test # visit me at http://${NAME}-solr.test/solr !
    - traefik.port=8983
    - traefik.docker.network=common-apps_default
    networks:
    - default
    - common-apps_default
    entrypoint: bash -c "cp -fr /myconfig/* solr/collection1/conf/; java -Xmx1024m -DSTOP.PORT=8984 -DSTOP.KEY=stopkey -jar start.jar"
networks:
  common-apps_default:
    external: true