<?php

/**
 * @file
 * Contains cri_tools.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
/**
 * Implements hook_help().
 */
function cri_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cri_tools module.
    case 'help.page.cri_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function cri_tools_menu_local_tasks_alter(&$data, $route_name) {

  kint($data);

  // Add a tab linking to node/add to all pages.
  $data['tabs'][0]['entity.taxonomy_term.canonical'] = array(
    '#theme' => 'menu_local_task',
    '#link' => array(
      'title' => t('Example tab'),
      'url' => Url::fromRoute('node.add_page'),
      'localized_options' => array(
        'attributes' => array(
          'title' => t('Add content'),
        ),
      ),
    ),
  );
}
