<?php

/**
 * @file
 * Contains cri_tools.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\taxonomy\Entity\Term;


/**
 * Implements hook_help().
 */
function cri_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cri_tools module.
    case 'help.page.cri_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function cri_tools_set_term_lang() {
$term = Term::load(6);
//$term->field_league_id->setValue('ID value');

//$term->language();
//  dd($term);$term


  // Get the current node's language.
  dd($term->get('langcode')->value);



// Set the current node's language.
  $term->set('langcode', 'es');
// Save the node to persist the change.
//  $node->save();

$term->save();
}