<?php

/**
 * @file
 * Contains cristina_migrate.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cristina_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cristina_migrate module.
    case 'help.page.cristina_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cristina migrate') . '</p>';
      return $output;

    default:
  }
}
